### ISSUE TITLE
[Pieces] Design basic pieces system 

### ISSUE THREAD

**Issue by nkuang123** [ThirdBlockStudios/Tetris2D#5]
Address the following in design:
- Data representation of the following 7 pieces
![image](https://github.com/ThirdBlockStudios/Tetris2D/assets/21281448/fcc9c2d0-c8f6-43fd-a4bc-b7a2fe9a7661)
- Interaction/behavior with board e.g. how will pieces be stored when placed?
- Nodes/scenes needed i.e. 2DSprite

We'll deal with the following separately down-the-line:
- Piece collision detection
- Line clearing
- Piece RNG queue
- Piece storing

**Comment by nkuang123** [comment]
@rp282 document design here whenever you can. Basically what we already discussed.

**Comment by rp282** [comment]
![image](https://github.com/ThirdBlockStudios/Tetris2D/assets/26453068/cc191d9e-0a90-4b1e-8868-d6ffd8f1eb01)

Each piece has a specific rotation origin. To achieve this the Piece scene will offset its child blocks by a 2D vector to appropriately align to (0,0)

**Comment by rp282** [comment]
Array _block_type_data_ stores the two variable block positions and correct rotation centers.

**Comment by nkuang123** [comment]
Done
